services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend/public:/var/www/html/public:ro
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    networks:
      - yrtuber-net
    restart: unless-stopped

  # Quasar frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:9000"  # Fixed: Map host 3000 to container 9000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=${FRONTEND_HOST:-0.0.0.0}
      - PORT=${FRONTEND_INTERNAL_PORT:-9000}
    command: ["quasar", "dev", "--host", "0.0.0.0", "--port", "9000"]
    depends_on:
      - backend
    networks:
      - yrtuber-net

  # Laravel Backend (API) - running as php-fpm
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE:-yrtuber}
      - DB_USERNAME=${MYSQL_USER:-yrtuber}
      - DB_PASSWORD=${MYSQL_PASSWORD:-password}
      - SESSION_LIFETIME=1440
      - SESSION_EXPIRE_ON_CLOSE=false
    networks:
      - yrtuber-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "php artisan inspire"]
      interval: 15s
      timeout: 10s
      retries: 3

  # MySQL Database
  db:
    image: mysql:8.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-yrtuber}
      - MYSQL_USER=${MYSQL_USER:-yrtuber}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - yrtuber-net

  # Optional: Adminer for DB access
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  # Fixed: Use port 8080 (was 8090)
    networks:
      - yrtuber-net

volumes:
  db_data:
  backend_storage:

networks:
  yrtuber-net:
    driver: bridge
