services:
  # Quasar frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:9000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=9000
    command: ["quasar", "dev"]
    depends_on:
      - backend
    networks:
      - yrtuber-net

  # Laravel Backend (API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=yrtuber
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - yrtuber-net

  # MySQL Database
  db:
    image: mysql:8.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yrtuber
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - yrtuber-net

  # Optional: Adminer for DB access
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - yrtuber-net

volumes:
  db_data:

networks:
  yrtuber-net:
    driver: bridge
